subjects:
  - 数学
  - 物理
  - 生物
  - 化学
  - 英语
  - 语文
  - 地理
  - 政治
  - 历史
  - 科学

categories:
  - 高中
  - 初中
  - 小学

grades_in_sorts:
  - 高三
  - 高二
  - 高一
  - 初三
  - 初二
  - 初一
  - 六年级
  - 五年级
  - 四年级
  - 三年级
  - 二年级
  - 一年级
grades_in_menu:
  - 高一
  - 高二
  - 高三
  - 初一
  - 初二
  - 初三
  - 一年级
  - 二年级
  - 三年级
  - 四年级
  - 五年级
  - 六年级
  

grades:
  高中:
    - 高一
    - 高二
    - 高三
  初中:
    - 初一
    - 初二
    - 初三
  小学:
    - 一年级
    - 二年级
    - 三年级
    - 四年级
    - 五年级
    - 六年级
subjects_of_grade:
  小学:
    - 语文
    - 数学
    - 英语
  初中:
    - 语文
    - 数学
    - 英语
    - 物理
    - 化学
    - 生物
    - 地理
    - 政治
    - 历史
    - 科学
  高中:
    - 语文
    - 数学
    - 英语
    - 物理
    - 化学
    - 生物
    - 地理
    - 政治
    - 历史
    - 科学
english:
  数学: math
  物理: physics
  生物: biology
  化学: chemistry
  英语: english
  历史: history
  地理: geography
  政治: politics
  语文: chinese
  科学: science

vip_class_ids:
  高中:
    数学: 1
    物理: 2
    化学: 3
    生物: 4
    英语: 9
    地理: 10
  初中:
    数学: 5
    物理: 6
    化学: 7
    生物: 8

vip_class_icons:
  数学:
    icon: fa fa-calculator fa-2x
  物理:
    icon: fa fa-rocket fa-2x
  化学:
    icon: fa fa-flask fa-2x
  生物:
    icon: fa fa-leaf fa-2x
  英语:
    icon: fa fa-language fa-2x
  地理:
    icon: fa fa-globe fa-2x

learning_plan:
  duration_types:
    半个月:
      price: 400
      time: 2.week
    一个月:
      price: 900
      time: 1.month
    三个月:
      price: 2500
      time: 3.month
    新建:
      price: -1
      time: 1.year

lesson_categories:
  default:
    - 知识点讲解
    - 常见问题
    - 易错点分析
    - 期中考试重点
    - 期末考试重点
    - 应试技巧
    - 解题方法与思路
  初中:
    default:
      - 中考重点
  高中:
    default:
      - 会考重点
      - 高考重点
  小学:
    default:
      - 小升初重点

handle_timeout: 1.day

price_per_minute: 0.9

customized_course_junior_common_prices:
  heighten:
    teacher_price: 42
    platform_price: 21
  spurt:
    teacher_price: 51
    platform_price: 21
  competition:
    teacher_price: 60
    platform_price: 21

customized_course_junior_high_common_prices:
  heighten:
    teacher_price: 45
    platform_price: 21
  spurt:
    teacher_price: 54
    platform_price: 21
  competition:
    teacher_price: 72
    platform_price: 21


customized_course_senior_high_common_prices:
  heighten:
    teacher_price: 54
    platform_price: 21
  spurt:
    teacher_price: 72
    platform_price: 21
  competition:
    teacher_price: 90
    platform_price: 21

invitation_statuses:
  - 已发送
  - 已接受
  - 已拒绝
  - 已过期
  - 已取消
